### ISSUE TITLE
Simplified installation

### ISSUE THREAD

**Issue by joperea** [MSU-CEDAR/cedarmapper#10]
1. Create run cedar function, that launches the app
2. test install from github (windows)
3. Write instructions

**Comment by billspat** [comment]
2b318882ebe2c2ae9d295f695059cfc908ab3c7c fixes 1 above.

**Comment by billspat** [comment]
Packages like ours list Dependencies in the file DESCRIPTION.  Those package dependencies have dependencies of their own, which R will install automatically when installing from CRAN. however  devtools::install_github() does not install the sub-dependencies automatically, and will fail even if those dependencies are never needed, per bug https://github.com/hadley/devtools/issues/1298   as of Feb 2017     Our solution is to discover full sub-deps tree and list them all in our DESCRIPTION file, OR have the user install the dependencies that cause installation fail manually and try again

**Comment by billspat** [comment]
826c1b558ff0a836e1807f2d74e9c17091c42f62 Includes new install instructions in main readme.   Needs testing on Windows and Mac.
