### ISSUE TITLE
Filter equalization

### ISSUE THREAD

**Issue by joperea** [MSU-CEDAR/cedarmapper#15]
Use histogram equalization to prevent nodes with too many data points. Owner: Paul

**Comment by billspat** [comment]
closed by pull request 26  https://github.com/MSU-CEDAR/cedarmapper/pull/26

**Comment by billspat** [comment]
closed by Paul's pull request 26  https://github.com/MSU-CEDAR/cedarmapper/pull/26

**Comment by billspat** [comment]
re-opening for new pull request
