### ISSUE TITLE
make all variables availlable to select for lense projection parameter, even if unselected

### ISSUE THREAD

**Issue by billspat** [MSU-CEDAR/cedarmapper#76]
users can de-select a variable so it's not used in the pipeline, but it may be valuable to use that variable as projection lense, but exclude it from partitioning or use in other dimension-reduction lenses (e.g. PCA, eccentricity etc).     When building list of available variables to for lense.projection function, don't check the selected variables - include all the variables. 

if there is variable/column the user NEVER wants to use (e.g. nuisance columns like IDs, or Row number that sometimes show up in datasets), create a way to remove those from the dataset entirely.

**Comment by joperea** [comment]
Getting errors when selected data only has one column:
Data: Circle
Variables: x 
Lens: Projection onto y coordinate 
*****
error: 

Warning: Error in <-: 'names' attribute [2] must be the same length as the vector [0]
Stack trace (innermost first):
    68: nodes.mapper
    67: mapper.run
    66: observeEventHandler [C:\Users\joperea\Documents\R\win-library\3.3\cedar\cedar/server.R#398]
     2: shiny::runApp
     1: cedar::runCedar
ERROR: [on_request_read] connection reset by peer

**Comment by billspat** [comment]
closing this issue but opened new specific issue #91
