### ISSUE TITLE
Show info on keyboard functionality

### ISSUE THREAD

**Issue by joperea** [MSU-CEDAR/cedarmapper#88]
Need to add a list of keyboard functionality:

A : select all
D : de-selected all
S : stick all
U : Unstick all
R : rotate right
L : rotate left
(plus): increase size of nodes
(minus): reduce size of nodes
] : increase width of edges
[ : reduce width of edges

Placement: no idea

**Comment by billspat** [comment]
add these to an additional  'tab' in the control menu like the original https://adminlte.io/themes/AdminLTE/index2.html does 

currently our control menu does not use tabs
