### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by joperea** [MSU-CEDAR/cedarmapper#9]
Firefox: applying the filter (selecting the node) removes the node

Chrome: when selecting groups, the halo is not pronounced

**Comment by billspat** [comment]
in FF, if the web inspector is turned on, then the nodes don't disappear, which indicates a bug in FF.

**Comment by billspat** [comment]
in Chrome, to get the glow or halo on nodes, need to add the filter attribute to the circle itself, not just in css stylesheet.  Eg. see http://dahlström.net/svg/filters/arrow-with-dropshadow.svg  

```<circle filter="url(#dropshadow)">```

When nodes are selected, and D3 dispatch is fired, sett attributes on selected nodes.   will need to create 3 filters, group1,group2, bothGroups
